import React from "react";
import Head from "next/head";
import Input from "../components/Input";
import Button from "../components/Button";
import Wrapper from "../components/Wrapper";
import SocialLinks from "../components/SocialLinks";

export default function Home() {
  const [login, setLogin] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [loginError, setLoginError] = React.useState(false);
  const [passwordError, setPasswordError] = React.useState(false);
  const [pinValido, setPinValido] = React.useState(false);
  const [loading, setLoading] = React.useState(false);

  function handleLogin() {
    setLoading(true);
    const handle = () => {
      return new Promise((resolv, reject) => {
        setTimeout(() => {
          resolv()
        }, 2000)
      })
    }

    setLoading(true)
    handle().then(() => {
      setLoading(false)
      setPinValido(old => !old)
    })
    // setPinValido((old) => !old);
  }

  const handlePasswordBlur = React.useCallback(() => {
    setPasswordError(password.length < 5);
  }, [password]);

  const FormInicial = () => {
    return (
      <>
        <Input error={false} onChange={(e) => console.log(e)} placehold="Pin" />
        <Button label="Validar" onClick={handleLogin} />
      </>
    );
  };

  const FormLogin = () => {
    return (
      <>
        <Input
          error={false}
          onChange={(e) => console.log(e)}
          placehold="E-mail"
        />
        <Input
          error={false}
          onChange={(e) => console.log(e)}
          placehold="Password"
        />
        
        <Button label="Entrar" onClick={handleLogin} />
        <section style={{
          padding: 20
        }}>
          <a className="forgot text-muted" href="#">
            Esqueceu sua senha?
          </a>
        </section>
        <SocialLinks />
      </>
    );
  };

  return (
    <div>
      <Head>
        <title>Entre na plataforma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main">
        <Wrapper title="SID">
          <p className="text-muted"> Entre com suas credênciais</p>

          {loading ? (
            <div className="spinner-border text-primary" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          ) : (
            <>{pinValido ? <FormLogin /> : <FormInicial />}</>
          )}
        </Wrapper>
      </div>
    </div>
  );
}
