import React from "react";
import Head from "next/head";
import Input from "../components/Input";
import Button from "../components/Button";
import Wrapper from "../components/Wrapper";

export default function Home() {
  const [login, setLogin] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [loginError, setLoginError] = React.useState(false);
  const [passwordError, setPasswordError] = React.useState(false);
  const [pinValido, setPinValido] = React.useState(false);
  const [loading, setLoading] = React.useState(false);

  function handleLogin() {
    setLoading(true);

    setTimeout(() => {
      setLoading(false);
    }, 2000);
    // setPinValido((old) => !old);
  }

  const handlePasswordBlur = React.useCallback(() => {
    setPasswordError(password.length < 5);
  }, [password]);

  const FormInicial = () => {
    return (
      <>
        <Input error={false} onChange={(e) => console.log(e)} placehold="Pin" />
        <Button label="Validar" onClick={handleLogin} />
      </>
    );
  };

  const FormLogin = () => {
    return (
      <>
        <Input
          error={false}
          onChange={(e) => console.log(e)}
          placehold="E-mail"
        />
        <Input
          error={false}
          onChange={(e) => console.log(e)}
          placehold="Password"
        />
        <a className="forgot text-muted" href="#">
          Esqueceu sua senha?
        </a>
        <input
          type="submit"
          onClick={handleLogin}
          name=""
          value="Entrar"
          href="#"
        />
        <div className="col-md-12">
          <ul className="social-network social-circle">
            <li>
              <a href="#" className="icoFacebook" title="Facebook">
                <i className="fab fa-facebook-f"></i>
              </a>
            </li>
            <li>
              <a href="#" className="icoTwitter" title="Twitter">
                <i className="fab fa-twitter"></i>
              </a>
            </li>
            <li>
              <a href="#" className="icoGoogle" title="Google +">
                <i className="fab fa-google-plus"></i>
              </a>
            </li>
          </ul>
        </div>
      </>
    );
  };

  return (
    <div>
      <Head>
        <title>Entre na plataforma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main">
        <Wrapper title="SID">
          <p className="text-muted"> Entre com suas credênciais</p>

          {loading ? (
            <div className="spinner-border text-primary" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          ) : (
            <>{pinValido ? <FormLogin /> : <FormInicial />}</>
          )}
        </Wrapper>
      </div>
    </div>
  );
}
